### ISSUE TITLE
I should be: 113

### ISSUE THREAD

**Issue by colesnicov** [AndFroSwe/MPU9250-RPi#1]
Hi i try to run this but i get this outputs:
`Starting program...`
`Connecting to IMU...`
`I am: 115`
`I should be: 113`
`Terminating...`

My mpu is connected to I2C(1) i machine is RPI 2 B.

**Comment by AndFroSwe** [comment]
I am sorry to say that I cannot help you with this issue since this project is on hold until further notice.

**Comment by colesnicov** [comment]
It's ok :)
